version: '3'
services:
    mysql:
        image: "mysql:8.0"
        container_name: mysql
        ports:
            - "3306:3306"
        networks:
            - front-tier
        volumes:
            - /home/mysql/data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "bonjour-Dev@2025"
    pay-server:
        image: "sesame-pay-server:v1"
        container_name: pay-server
        ports:
            - "30001:30001"
        networks:
            - front-tier
        volumes:
            - /home/pay-server/logs:/logs
    web:
        image: "registry.cn-shanghai.aliyuncs.com/bonjoy/nginx:v1"
        container_name: web
        ports:
            - "80:80"
        networks:
            - front-tier
        volumes:
            - /home/web/html:/usr/share/nginx/html
            - /home/web/log:/var/log/nginx
            - /home/web/nginx.conf:/etc/nginx/nginx.conf
networks:
    front-tier:
        driver: bridge
        
        

